### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by therealscottcarlow** [ShadwDrgn/eap_proxy#1]
@ShadwDrgn First, thanks for whipping this up. I'm going to be in need of it real soon. I found my way here from your reply to a forum post.

Anyways, I'm happy to submit a PR with documentation, but my Python is rusty and was never very good to begin with. It looks like it's setting the interfaces to promiscuous mode to target EAP traffic and shuffle that traffic between the two interfaces. One interface needs to be connected to the AT&To gateway's WAN and the other to the ONT. Am I following so far?

You mentioned possibly needing to tag the traffic. Is the purpose for that just to isolate the traffic between the gateway and ONT to prevent routing conflicts with two identical MACs in the arp takes? Can you explain a bit the reasoning and proposed topology of the VLAN config?

Also, needing to spoof the modem's MAC on the ONT interface makes sense, no questions there.

Sorry to bombard you. I just want to make sure I have it straight before I get to work on implementing this myself and documenting the script.

Thanks!

**Comment by ShadwDrgn** [comment]
Sounds like you have it right other than the reason for the MAC change and vlan traffic tagging. The reason for possibly requiring VLAN tagging is just that the ONT may be using a tagged vlan. In my case it's VLAN 0, but some people have reported it being different. the MAC change is because AT&T won't hand out DHCP to anything but your modem's MAC.
